//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopSunday.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public int ID { get; set; }
        public int GameTypeID { get; set; }
        public int PlayerID { get; set; }
        public int NumGames { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Draws { get; set; }
        public int TotalPoints { get; set; }
        public string Resume { get; set; }
    
        public virtual Classification Classification1 { get; set; }
        public virtual Classification Classification2 { get; set; }
        public virtual GameTypes GameTypes { get; set; }
        public virtual Player Player { get; set; }
    }
}
