//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopSunday.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameTeams
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public int GameTypeID { get; set; }
        public System.DateTime GameDate { get; set; }
    }
}
